#!/usr/bin/env python3
"""Fix remaining visible UTF-8 / emoji corruption in index.html (post git-restore pass)."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "src/api/templates/index.html"

# Order matters — longer / more specific patterns first.
REPLACEMENTS: list[tuple[str, str]] = [
    # Section comments
    ("/* ?? Command Center terminal layout ?? */", "/* ── Command Center terminal layout ── */"),
    ("/* ?? Guide / Onboarding ?? */", "/* ── Guide / Onboarding ── */"),
    ("// ?? DEAD-CODE WARNING (no UI binding, kept only because JS methods still reference them) ??",
     "// ── DEAD-CODE WARNING (no UI binding, kept only because JS methods still reference them) ──"),
    ("// ?? IBKR auto-sync: when broker is connected, broker positions become canonical ??",
     "// ── IBKR auto-sync: when broker is connected, broker positions become canonical ──"),
    ("// ?? Correlation guard: warn (>0.6) / block (>0.7) when adding correlated names ??",
     "// ── Correlation guard: warn (>0.6) / block (>0.7) when adding correlated names ──"),
    ("// ?? 24/7 Fund Monitor (sprint89) ??????????????????????????????????????",
     "// ── 24/7 Fund Monitor (sprint89) ──"),
    ("// ?? BRACKET ORDER (parent + stop + target, OCA) ?????????????????????????",
     "// ── BRACKET ORDER (parent + stop + target, OCA) ──"),
    ("// ?? Pre-trade slippage gate (BLOCK on illiquid; WARN on costly) ??",
     "// ── Pre-trade slippage gate (BLOCK on illiquid; WARN on costly) ──"),
    ("// ?? Bracket live polling + cancel ??????????????????????????????????????",
     "// ── Bracket live polling + cancel ──"),
    ("// ?? Playbook ? IBKR bracket helper ?????????????????????????????????????",
     "// ── Playbook → IBKR bracket helper ──"),
    ("// ?? PM Strip (model funds mini-cards, refreshed lazily) ????????????????",
     "// ── PM Strip (model funds mini-cards, refreshed lazily) ──"),
    ("// ?? Model Funds (productized fund cards) ??????????????????????????????",
     "// ── Model Funds (productized fund cards) ──"),
    ("// ?? Trade Intelligence ????????????????????????????????????????????????",
     "// ── Trade Intelligence ──"),
    # Time travel modal
    (
        "????????????????????????????????????????",
        "選擇回放日期 · 載入該日 Morning Brief 快照 · Dashboard + Playbook + 標頭同步切換 · Pick a date to replay the whole console from that day's brief.",
    ),
    ("x-text=\"tt.loading?'? Loading?':'? Enter replay'\"", "x-text=\"tt.loading?'⏳ Loading…':'⏪ Enter replay'\""),
    ("x-text=\"tt.loading?'? Running?':'? Run replay'\"", "x-text=\"tt.loading?'⏳ Running…':'▶ Run replay'\""),
    (".join(' ? ')", ".join(' · ')"),
    ("? I Understand ? Proceed", "✓ I Understand · Proceed"),
    ("? Position Risk Alerts", "⚠ Position Risk Alerts"),
    (">? Refresh</button>", ">↻ Refresh</button>"),
    (">? Load</button>", ">↻ Load</button>"),
    (">? Rotate</button>", ">🔄 Rotate</button>"),
    ("? No active risk alerts.", "✓ No active risk alerts."),
    ("? Strategy signals", "📊 Strategy signals"),
    ("Pick a ticker + date ? see regime", "Pick a ticker + date · see regime"),
    ("Pick a date ? Enter replay loads", "Pick a date · Enter replay loads"),
    ("trust.as_of?'? '+", "trust.as_of?'🕐 '+"),
    (">? AI</span>", ">✨ AI</span>"),
    ("apiError.startsWith('?')?'color:#fde68a", "apiError.startsWith('⚠')?'color:#fde68a"),
    ("x-show=\"apiError.startsWith('?')\"", "x-show=\"apiError.startsWith('⚠')\""),
    ("'Uptime: '+(healthData?.uptime_seconds?Math.round(healthData.uptime_seconds)+'s':'?')", "'Uptime: '+(healthData?.uptime_seconds?Math.round(healthData.uptime_seconds)+'s':'—')"),
    # Command / agent
    ("<span style=\"font-size:13px\">??</span>", "<span style=\"font-size:13px\">⚠️</span>"),
    ("<span style=\"font-size:14px\">??</span>", "<span style=\"font-size:14px\">⚠️</span>"),
    ("? SYNTHETIC ? Regime data is synthetic", "⚠ SYNTHETIC · Regime data is synthetic"),
    ("? Morning briefing", "📰 Morning briefing"),
    ("Intent inbox ? rule builder", "Intent inbox · rule builder"),
    ("?? Agent ?? ? Monitor only", "🤖 Agent · 監察 · Monitor only"),
    ("Agent ? Monitor copilot", "Agent · Monitor copilot"),
    ("No degraded note ? active monitor copilot.", "No degraded note · active monitor copilot."),
    (">?? Agent Journal</summary>", ">📝 Agent Journal</summary>"),
    (">?? Agent Reliability</summary>", ">📊 Agent Reliability</summary>"),
    (">? Starred</div>", ">⭐ Starred</div>"),
    ("click ? Refresh to load", "click ↻ Refresh to load"),
    (">? SYNTHETIC</span>", ">⚠ SYNTHETIC</span>"),
    (">? Why Now</div>", ">💡 Why Now</div>"),
    (">? Contradictions</div>", ">⚖ Contradictions</div>"),
    ("Loading decisions?", "Loading decisions…"),
    ("x-text=\"'🕐 '+topMonitorLabelsLine()\"", "x-text=\"'· '+topMonitorLabelsLine()\""),
    ("x-text=\"'? '+topMonitorLabelsLine()\"", "x-text=\"'· '+topMonitorLabelsLine()\""),
    # Dashboard / opportunities
    (">?? Top Opportunities</summary>", ">🎯 Top Opportunities</summary>"),
    ("Regime snapshot ? expand", "Regime snapshot · expand"),
    ("Unlock deploy ? expand", "Unlock deploy · expand"),
    ("? AI Commentary ? expand", "✨ AI Commentary · expand"),
    (">? What Changed</div>", ">📈 What Changed</div>"),
    ("title=\"Star (favorite)\" @click=\"toggleStar(opp.ticker)\">?</button>",
     "title=\"Star (favorite)\" @click=\"toggleStar(opp.ticker)\">★</button>"),
    ("title=\"Love (high conviction)\" @click=\"toggleLove(opp.ticker)\">?</button>",
     "title=\"Love (high conviction)\" @click=\"toggleLove(opp.ticker)\">♥</button>"),
    ("?? Strong thesis, weak timing ? wait for better entry before acting",
     "⚠ Strong thesis, weak timing · wait for better entry before acting"),
    ("?? Good timing but weak thesis ? low conviction, size down or skip",
     "⚠ Good timing but weak thesis · low conviction, size down or skip"),
    ("?? Good setup but execution risk high ? use limit orders, reduce size by 50%",
     "⚠ Good setup but execution risk high · use limit orders, reduce size by 50%"),
    ("?? Strong thesis, weak timing ? wait for pullback",
     "⚠ Strong thesis, weak timing · wait for pullback"),
    ("?? Good timing, weak thesis ? low conviction",
     "⚠ Good timing, weak thesis · low conviction"),
    (">?? Vol?</span>", ">📈 Vol✓</span>"),
    (">??ER Blackout</span>", ">📅 ER Blackout</span>"),
    (">?? Earnings Blackout</span>", ">📅 Earnings Blackout</span>"),
    ("?? <strong style=\"color:var(--t1)\">PILOT</strong> when: partial edge with stop ? review-only",
     "🧪 <strong style=\"color:var(--t1)\">PILOT</strong> when: partial edge with stop · review-only"),
    ("?? <strong style=\"color:var(--t1)\">Historical Win Rate</strong> shown when ?10 similar past trades exist ? use as extra confirmation",
     "📊 <strong style=\"color:var(--t1)\">Historical Win Rate</strong> shown when ≥10 similar past trades exist · use as extra confirmation"),
    ("board-ranked score ?8, thesis+timing ?65%, R:R ?2.5", "board-ranked score ≥8, thesis+timing ≥65%, R:R ≥2.5"),
    ("ranked #1?10 but below TRADE bar (score 6?8", "ranked #1–10 but below TRADE bar (score 6–8"),
    ("Green ?70%</span> ? <span", "Green ≥70%</span> · <span"),
    ("Amber ?50%</span> ? <span", "Amber ≥50%</span> · <span"),
    ("<span style=\"color:var(--green)\">?</span> <strong style=\"color:var(--t1)\">BUY</strong> ? Enter now",
     "<span style=\"color:var(--green)\">●</span> <strong style=\"color:var(--t1)\">BUY</strong> · Enter now"),
    ("<strong style=\"color:var(--t1)\">BUY_ON_DIP</strong> ? Good setup", "<strong style=\"color:var(--t1)\">BUY_ON_DIP</strong> · Good setup"),
    ("<span style=\"color:var(--amber)\">?</span> <strong style=\"color:var(--t1)\">WATCH</strong> ? Monitor",
     "<span style=\"color:var(--amber)\">●</span> <strong style=\"color:var(--t1)\">WATCH</strong> · Monitor"),
    ("<strong style=\"color:var(--t1)\">WAIT</strong> ? Regime unfavorable", "<strong style=\"color:var(--t1)\">WAIT</strong> · Regime unfavorable"),
    ("<span style=\"color:var(--red)\">?</span> <strong style=\"color:var(--t1)\">AVOID</strong> ? Extended",
     "<span style=\"color:var(--red)\">●</span> <strong style=\"color:var(--t1)\">AVOID</strong> · Extended"),
    ("? <strong style=\"color:var(--t1)\">Full TRADE</strong> when:", "● <strong style=\"color:var(--t1)\">Full TRADE</strong> when:"),
    ("? <strong style=\"color:var(--t1)\">Watch</strong> when:", "● <strong style=\"color:var(--t1)\">Watch</strong> when:"),
    ("? Tradeability improves to SELECTIVE+", "● Tradeability improves to SELECTIVE+"),
    ("<div>? At least 1 deploy-qualified setup exists</div>", "<div>● At least 1 deploy-qualified setup exists</div>"),
    ("<div>? Broker handoff is live</div>", "<div>● Broker handoff is live</div>"),
    ("<div>? Board-level quality supports risk (?1 watch-qualified name on fresh data)</div>",
     "<div>● Board-level quality supports risk (≥1 watch-qualified name on fresh data)</div>"),
    ("x-text=\"(c.met?'? ':'? ')+c.label\"", "x-text=\"(c.met?'✓ ':'○ ')+c.label\""),
    ("x-text=\"'? '+(Array.isArray(today7.top_ranked[0].why_now)", "x-text=\"'✓ '+(Array.isArray(today7.top_ranked[0].why_now)"),
    ("x-text=\"'? Invalidation: '+today7.top_ranked[0].invalidation\"", "x-text=\"'✕ Invalidation: '+today7.top_ranked[0].invalidation\""),
    ("x-text=\"'? '+ln\"", "x-text=\"'• '+ln\""),
    ("x-text=\"'? '+c\"", "x-text=\"'• '+c\""),
    ("x-text=\"'? '+eventRiskLabel", "x-text=\"'📅 '+eventRiskLabel"),
    ("x-text=\"'? '+nm.upgrade_trigger\"", "x-text=\"'→ '+nm.upgrade_trigger\""),
    ("x-text=\"'✓ '+nm.upgrade_trigger\"", "x-text=\"'→ '+nm.upgrade_trigger\""),
    ("x-text=\"'? '+cc.upgrade_trigger\"", "x-text=\"'→ '+cc.upgrade_trigger\""),
    ("x-text=\"'? '+rb\"", "x-text=\"'⛔ '+rb\""),
    ("x-text=\"'? '+(nm.upgrade_trigger||'')\"", "x-text=\"'→ '+(nm.upgrade_trigger||'')\""),
    (
        "x-text=\"'? '+today7.cross_asset_confirmation.confirms.join(' · ')\"",
        "x-text=\"'✓ '+today7.cross_asset_confirmation.confirms.join(' · ')\"",
    ),
    (
        "x-text=\"'? '+today7.cross_asset_confirmation.conflicts.join(' · ')\"",
        "x-text=\"'⚠ '+today7.cross_asset_confirmation.conflicts.join(' · ')\"",
    ),
    (
        '<div x-show="!((today7.evidence_conflict||{}).for||[]).length" style="color:var(--t3)">?</div>',
        '<div x-show="!((today7.evidence_conflict||{}).for||[]).length" style="color:var(--t3)">—</div>',
    ),
    (
        '<div x-show="!((today7.evidence_conflict||{}).against||[]).length" style="color:var(--t3)">?</div>',
        '<div x-show="!((today7.evidence_conflict||{}).against||[]).length" style="color:var(--t3)">—</div>',
    ),
    ("<!-- ── Decision hierarchy L1?L5 (collapsible) ── -->", "<!-- ── Decision hierarchy L1–L5 (collapsible) ── -->"),
    (">? Sector Leaders</div>", ">📈 Sector Leaders</div>"),
    (">? Sector Laggards</div>", ">📉 Sector Laggards</div>"),
    (
        '<span style="color:var(--green)">?</span> <strong style="color:var(--t1)">BUY_ON_DIP</strong>',
        '<span style="color:var(--green)">●</span> <strong style="color:var(--t1)">BUY_ON_DIP</strong>',
    ),
    (
        '<span style="color:var(--amber)">?</span> <strong style="color:var(--t1)">WAIT</strong>',
        '<span style="color:var(--amber)">●</span> <strong style="color:var(--t1)">WAIT</strong>',
    ),
    ('title="New entry vs yesterday\'s top list">? NEW</span>', 'title="New entry vs yesterday\'s top list">✨ NEW</span>'),
    (
        ":title=\"'Moved up '+opp._diffMove+' rank(s) since yesterday'\">?<span x-text=\"opp._diffMove\"></span></span>",
        ":title=\"'Moved up '+opp._diffMove+' rank(s) since yesterday'\">↑<span x-text=\"opp._diffMove\"></span></span>",
    ),
    (
        ":title=\"'Dropped '+Math.abs(opp._diffMove)+' rank(s) since yesterday'\">?<span x-text=\"Math.abs(opp._diffMove)\"></span></span>",
        ":title=\"'Dropped '+Math.abs(opp._diffMove)+' rank(s) since yesterday'\">↓<span x-text=\"Math.abs(opp._diffMove)\"></span></span>",
    ),
    ("x-text=\"'? '+opp.conflict_level+' conflict'\"", "x-text=\"'⚖ '+opp.conflict_level+' conflict'\""),
    (">?Gate</span>", ">⛔ Gate</span>"),
    (
        "x-text=\"'? '+(Array.isArray(opp.why_now)?opp.why_now.join(' · '):opp.why_now)\"",
        "x-text=\"'✓ '+(Array.isArray(opp.why_now)?opp.why_now.join(' · '):opp.why_now)\"",
    ),
    ("x-text=\"'? '+opp.invalidation\"", "x-text=\"'✕ '+opp.invalidation\""),
    (
        '<template x-for="r in (opp.reasons_against||[]).slice(0,4)">\n                      <div class="text-[8px]" style="color:var(--red);line-height:1.4" x-text="\'? \'+r"></div>',
        '<template x-for="r in (opp.reasons_against||[]).slice(0,4)">\n                      <div class="text-[8px]" style="color:var(--red);line-height:1.4" x-text="\'✗ \'+r"></div>',
    ),
    (
        '<template x-for="r in (opp.pre_mortem||[]).slice(0,2)">\n                      <div class="text-[8px]" style="color:var(--amber);line-height:1.4" x-text="\'? \'+r"></div>',
        '<template x-for="r in (opp.pre_mortem||[]).slice(0,2)">\n                      <div class="text-[8px]" style="color:var(--amber);line-height:1.4" x-text="\'⚠ \'+r"></div>',
    ),
    ("x-text=\"'? '+opp.why_wait\"", "x-text=\"'⏳ '+opp.why_wait\""),
    ("x-text=\"'? '+opp.timing\"", "x-text=\"'⏱ '+opp.timing\""),
    ("? Review the <strong style=\"color:var(--t1)\">Watchlist</strong>", "● Review the <strong style=\"color:var(--t1)\">Watchlist</strong>"),
    ("? Check <strong style=\"color:var(--t1)\">Regime</strong> ? if NO_TRADE", "● Check <strong style=\"color:var(--t1)\">Regime</strong> · if NO_TRADE"),
    ("? Use <strong style=\"color:var(--t1)\">Scanners</strong>", "● Use <strong style=\"color:var(--t1)\">Scanners</strong>"),
    ("? Cash is a position ? not trading is a valid decision", "● Cash is a position · not trading is a valid decision"),
    ("x-text=\"'? '+marketStrip.error.slice(0,28)\"", "x-text=\"'⚠ '+marketStrip.error.slice(0,28)\""),
    (">? Refresh market data</button>", ">↻ Refresh market data</button>"),
    ("Loading market data?</div>", "Loading market data…</div>"),
    (">? Retry sectors</button>", ">↻ Retry sectors</button>"),
    ("(XLK, XLF, XLE?) will appear", "(XLK, XLF, XLE…) will appear"),
    (
        "x-text=\"'?RS '+Math.round(opp.rs.rs_composite)+(opp.rs.rs_slope>0?' ?':opp.rs.rs_slope<0?' ?':'')\"",
        "x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.dashboardRsPillLabel)?CCHelpers.dashboardRsPillLabel(opp.rs):('📈 RS '+Math.round(opp.rs.rs_composite))\"",
    ),
    ("x-text=\"'⚠ '+(Array.isArray(opp.why_not)", "x-text=\"'⚠ '+(Array.isArray(opp.why_not)"),
    ("x-text=\"'⚠ '+(Array.isArray(r.why_not)", "x-text=\"'⚠ '+(Array.isArray(r.why_not)"),
    ("x-text=\"'⚠ '+ln\"", "x-text=\"'✗ '+ln\""),
    ("x-text=\"'⚠ '+rb\"", "x-text=\"'⛔ '+rb\""),
    ("x-text=\"'⚠ '+today7.cross_asset_confirmation.conflicts.join", "x-text=\"'⚠ '+today7.cross_asset_confirmation.conflicts.join"),
    ("x-text=\"'✓ '+today7.cross_asset_confirmation.confirms.join", "x-text=\"'✓ '+today7.cross_asset_confirmation.confirms.join"),
    # Strategy lab / discovery / ops
    (
        "????? ? Draft <span class=\"mono text-white\" x-text=\"stratLabDraft.draftId\"></span> ? ???? Playbook ???????????????",
        "草稿已建立 · Draft <span class=\"mono text-white\" x-text=\"stratLabDraft.draftId\"></span> · 尚未同步 Playbook · not yet promoted",
    ),
    ("x-text=\"stratLabDraft.generating?'?':researchGettingStarted('strategy').nextButton\"", "x-text=\"stratLabDraft.generating?'⏳':researchGettingStarted('strategy').nextButton\""),
    ("Raw scanner hits ? similar-pattern cluster ? debug", "Raw scanner hits · similar-pattern cluster · debug"),
    ("'hidden ? 0 strict passed'", "'hidden · 0 strict passed'"),
    (
        "x-text=\"catName==='FLOW'?'💧':catName==='VALIDATION'?'✓':catName==='PATTERN'?'📐':catName==='SECTOR'?'??':catName==='RISK'?'?':'??'\"",
        "x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.signalCategoryIcon)?CCHelpers.signalCategoryIcon(catName):(catName==='FLOW'?'💧':catName==='VALIDATION'?'✓':catName==='PATTERN'?'📐':catName==='SECTOR'?'🏭':catName==='RISK'?'⚠':'📦')\"",
    ),
    (":disabled=\"ledgerView.loading\">??</button>", ":disabled=\"ledgerView.loading\">↻</button>"),
    ("x-text=\"ledgerView.expanded?'? Hide details':'? Show details ('+(ledgerView.rows?.length||0)+' rows)'\"",
     "x-text=\"ledgerView.expanded?'▾ Hide details':'▸ Show details ('+(ledgerView.rows?.length||0)+' rows)'\""),
    (">?? Health</button>", ">💚 Health</button>"),
    (">?? Engine State</div>", ">⚙ Engine State</div>"),
    (">?? IBKR</button>", ">⚡ IBKR</button>"),
    ("placeholder=\"Search ticker or company? (e.g. AAPL, ??)\"",
     "placeholder=\"Search ticker or company name (e.g. AAPL, 苹果)\""),
    ("x-text=\"'?' + (rl.thompson.best_arm.mean_multiplier??'?')",
     "x-text=\"'×' + (rl.thompson.best_arm.mean_multiplier??'—')"),
    # Runtime JS — delegate to CCHelpers where possible
    ("let msg='?????? ? ???? Brief ???';", "let msg=(typeof CCHelpers!=='undefined'&&CCHelpers.replayBriefMissingError)?CCHelpers.replayBriefMissingError():'No Morning Brief snapshot for that date';"),
    ("this.showExportToast('??????? ? ???? Playbook ?????????');",
     "this.showExportToast((typeof CCHelpers!=='undefined'&&CCHelpers.stratLabDraftCreatedToast)?CCHelpers.stratLabDraftCreatedToast():'Draft created · not yet synced to Playbook');"),
    ("throw new Error('CSV ????????????');",
     "throw new Error((typeof CCHelpers!=='undefined'&&CCHelpers.shadowCsvEmptyError)?CCHelpers.shadowCsvEmptyError():'CSV needs headers and at least one row');"),
    ("throw new Error('???? CSV ? ? ???????');",
     "throw new Error((typeof CCHelpers!=='undefined'&&CCHelpers.shadowCsvImportEmptyError)?CCHelpers.shadowCsvImportEmptyError():'No valid CSV rows to import');"),
    ("this.showExportToast('??? '+imported+' ????? ? ?????');",
     "this.showExportToast((typeof CCHelpers!=='undefined'&&CCHelpers.shadowImportSuccessToast)?CCHelpers.shadowImportSuccessToast(imported):('Imported '+imported+' trades'));"),
    ("fundIcon(name){return name==='FUND_ALPHA'?'??':name==='FUND_PENDA'?'??':name==='FUND_MACRO'?'??':'??'},",
     "fundIcon(name){return (typeof CCHelpers!=='undefined'&&CCHelpers.fundIcon)?CCHelpers.fundIcon(name):(name==='FUND_ALPHA'?'🟢':name==='FUND_PENDA'?'🔵':name==='FUND_MACRO'?'🟣':'📦')},"),
    ("return 'Structure snapshot ? ????';", "return 'Structure snapshot · 結構快照';"),
    ("if(field==='entry') return 'Reference level ? ????';", "if(field==='entry') return 'Reference level · 參考價位';"),
    ("if(field==='stop') return 'Risk reference ? ????';", "if(field==='stop') return 'Risk reference · 風險參考';"),
    ("if(field==='target') return 'Upside references ? ????';", "if(field==='target') return 'Upside references · 上行參考';"),
    ("return 'Paper draft disabled ? ??????? ? ? live Dossier + Playbook ???????';",
     "return 'Paper draft disabled · 紙上模擬已關閉 — 需 live Dossier + Playbook 確認後才可模擬';"),
    ("// Auto-enable bracket if both stop + target are available ? close alpha?execution loop",
     "// Auto-enable bracket if both stop + target are available · close alpha→execution loop"),
    # Bilingual CC copy — separators and surface headers
    ("DISCOVERY ? Research Funnel", "研究漏斗 · Research Funnel"),
    ("可做 · Allowed", "允許 · Allowed"),
    ("<span class=\"font-bold uppercase\" style=\"color:var(--blue)\">下一步 · Next</span> ? <span x-text=\"dossierOperatorBlock().next\"></span>",
     "<span class=\"font-bold uppercase\" style=\"color:var(--blue)\">下一步 · Next</span> · <span x-text=\"dossierOperatorBlock().next\"></span>"),
    ("Curve ? deploy permission ? backtest ? live edge", "Curve · deploy permission · backtest · live edge"),
    ("{id:'guide',icon:'📖',label:'Guide · 指南'}", "{id:'guide',icon:'📖',label:'指南 · Guide'}"),
    ("{id:'today',icon:'🎯',label:'Dashboard · 看板'}", "{id:'today',icon:'🎯',label:'總覽 · Dashboard'}"),
    ("{id:'signals',icon:'📋',label:'Playbook · 候選'}", "{id:'signals',icon:'📋',label:'PM 看板 · Playbook'}"),
    ("{id:'scanners',icon:'🔬',label:'Discovery · 掃描'}", "{id:'scanners',icon:'🔬',label:'掃描 · Discovery'}"),
    ("{id:'portfolio',icon:'💼',label:'Portfolio · 持倉'}", "{id:'portfolio',icon:'💼',label:'組合 · Portfolio'}"),
    ("{id:'dossier',icon:'🔍',label:'Dossier · 研究檔'}", "{id:'dossier',icon:'🔍',label:'檔案 · Dossier'}"),
    ("<span class=\"font-bold uppercase\" style=\"color:var(--blue)\">Decision Quality</span>",
     "<span class=\"font-bold uppercase\" style=\"color:var(--blue)\" x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.decisionQualityHeader)?CCHelpers.decisionQualityHeader():'決策品質 · Decision Quality'\"></span>"),
    ("<summary class=\"text-[8px] font-bold cursor-pointer\" style=\"color:var(--purple,#a78bfa)\">ALPHA QUALITY · evidence only · authority effect: none</summary>",
     "<summary class=\"text-[8px] font-bold cursor-pointer\" style=\"color:var(--purple,#a78bfa)\" x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.alphaQualityCollapsedHeader)?CCHelpers.alphaQualityCollapsedHeader():'Alpha 品質 · Alpha Quality · 僅供研究 · evidence only · authority effect: none'\"></summary>"),
    ("<span>ALPHA REVIEW</span>", "<span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.alphaReviewCollapsedHeader)?CCHelpers.alphaReviewCollapsedHeader():'Alpha 複核 · Alpha Review'\"></span>"),
    ("<div class=\"text-[10px] font-bold uppercase mb-1\" style=\"color:var(--amber)\" x-text=\"'NOW: '+(pfDecision.portfolio_operator_block.now||'Risk review only')\"></div>",
     "<div class=\"text-[10px] font-bold uppercase mb-1\" style=\"color:var(--amber)\"><span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.operatorBlockChromeLabel)?CCHelpers.operatorBlockChromeLabel('now'):'Now'\"></span> <span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.portfolioOperatorBlockLocalized)?CCHelpers.portfolioOperatorBlockLocalized(pfDecision.portfolio_operator_block).now:(pfDecision.portfolio_operator_block.now||'Risk review only')\"></span></div>"),
    ("<span style=\"color:var(--t3)\">WHY:</span> <span x-text=\"pfDecision.portfolio_operator_block.why||'?'\"></span>",
     "<span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.operatorBlockChromeLabel)?CCHelpers.operatorBlockChromeLabel('why'):'Why'\"></span> <span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.portfolioOperatorBlockLocalized)?CCHelpers.portfolioOperatorBlockLocalized(pfDecision.portfolio_operator_block).why:(pfDecision.portfolio_operator_block.why||'—')\"></span>"),
    ("<span style=\"color:var(--t3)\">ALLOWED:</span> <span x-text=\"pfDecision.portfolio_operator_block.allowed||'risk review'\"></span>",
     "<span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.operatorBlockChromeLabel)?CCHelpers.operatorBlockChromeLabel('allowed'):'Allowed'\"></span> <span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.portfolioOperatorBlockLocalized)?CCHelpers.portfolioOperatorBlockLocalized(pfDecision.portfolio_operator_block).allowed:(pfDecision.portfolio_operator_block.allowed||'risk review')\"></span>"),
    ("<span style=\"color:var(--t3)\">BLOCKED:</span> <span x-text=\"pfDecision.portfolio_operator_block.blocked||'no capital actions'\"></span>",
     "<span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.operatorBlockChromeLabel)?CCHelpers.operatorBlockChromeLabel('blocked'):'Blocked'\"></span> <span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.portfolioOperatorBlockLocalized)?CCHelpers.portfolioOperatorBlockLocalized(pfDecision.portfolio_operator_block).blocked:(pfDecision.portfolio_operator_block.blocked||'no capital actions')\"></span>"),
    ("<span style=\"color:var(--t3)\">NEXT:</span> <span x-text=\"pfDecision.portfolio_operator_block.next||'reconcile broker'\"></span>",
     "<span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.operatorBlockChromeLabel)?CCHelpers.operatorBlockChromeLabel('next'):'Next'\"></span> <span x-text=\"(typeof CCHelpers!=='undefined'&&CCHelpers.portfolioOperatorBlockLocalized)?CCHelpers.portfolioOperatorBlockLocalized(pfDecision.portfolio_operator_block).next:(pfDecision.portfolio_operator_block.next||'reconcile broker')\"></span>"),
    ("<span class=\"pill text-[7px] pa\" x-text=\"'看板姿態 '+(isWaitDay()?'WAIT · 等待':'MONITOR · 僅監察')+' · Board stance '+(isWaitDay()?'WAIT':'MONITOR')\"></span>",
     "<span class=\"pill text-[7px] pa\" x-text=\"'看板姿態 '+(isWaitDay()?'WAIT · 等待':'MONITOR · 僅監控')+' · Board stance '+(isWaitDay()?'WAIT':'MONITOR')\"></span>"),
    ("title=\"One-click export all pages (issues + surfaces PDF)\"",
     "title=\"一鍵匯出全介面 · One-click export all pages (issues + surfaces PDF)\""),
]


def main() -> None:
    text = INDEX.read_text(encoding="utf-8")
    before = text.count("??")
    applied = 0
    for old, new in REPLACEMENTS:
        if old in text:
            text = text.replace(old, new)
            applied += 1
    INDEX.write_text(text, encoding="utf-8")
    text.encode("utf-8")
    after = text.count("??")
    print(f"applied {applied} visible UTF-8 replacements")
    print(f"total ?? count: {before} -> {after} (includes JS nullish coalescing)")


if __name__ == "__main__":
    main()
